In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train_set = pd.read_csv('train.csv')
test_set = pd.read_csv('test.csv')

In [3]:
test_set.head()

Employee_ID Gender   Age  Education_Level Relationship_Status     Hometown  \
0   EID_22713      F  32.0                5              Single  Springfield   
1    EID_9658      M  65.0                2              Single      Lebanon   
2   EID_22203      M  52.0                3             Married  Springfield   
3    EID_7652      M  50.0                5              Single   Washington   
4    EID_6516      F  44.0                3             Married     Franklin   

        Unit Decision_skill_possess  Time_of_service  Time_since_promotion  \
0        R&D             Conceptual              7.0                     4   
1         IT              Directive             41.0                     2   
2      Sales              Directive             21.0                     3   
3  Marketing             Analytical             11.0                     4   
4        R&D             Conceptual             12.0                     4   

   ...  Pay_Scale  Compensation_and_Benefits  Work_Life_balance  VAR1    VAR2  \
0  ...        4.0                      type2                1.0     3 -0.9612   
1  ...        1.0                      type2                1.0     4 -0.9612   
2  ...        8.0                      type3                1.0     4 -0.1048   
3  ...        2.0                      type0                4.0     3 -0.1048   
4  ...        2.0                      type2                4.0     4  1.6081   

     VAR3  VAR4  VAR5  VAR6  VAR7  
0 -0.4537   2.0     1     8     4  
1  0.7075   1.0     2     8     2  
2  0.7075   2.0     1     9     3  
3  0.7075   2.0     2     8     3  
4  0.7075   2.0     2     7     4  

[5 rows x 23 columns]

In [4]:
test_copy = test_set.copy()

In [5]:
train_set.drop('Employee_ID', inplace = True , axis = 1)
test_set.drop('Employee_ID', inplace = True , axis = 1)

In [6]:
train_set.head()

Gender   Age  Education_Level Relationship_Status     Hometown  \
0      F  42.0                4             Married     Franklin   
1      M  24.0                3              Single  Springfield   
2      F  58.0                3             Married      Clinton   
3      F  26.0                3              Single      Lebanon   
4      F  31.0                1             Married  Springfield   

                        Unit Decision_skill_possess  Time_of_service  \
0                         IT             Conceptual              4.0   
1                  Logistics             Analytical              5.0   
2                    Quality             Conceptual             27.0   
3  Human Resource Management             Behavioral              4.0   
4                  Logistics             Conceptual              5.0   

   Time_since_promotion  growth_rate  ...  Compensation_and_Benefits  \
0                     4           33  ...                      type2   
1                     4           36  ...                      type2   
2                     3           51  ...                      type2   
3                     3           56  ...                      type2   
4                     4           62  ...                      type3   

   Work_Life_balance  VAR1    VAR2    VAR3  VAR4  VAR5  VAR6  VAR7  \
0                3.0     4  0.7516  1.8688   2.0     4     5     3   
1                4.0     3 -0.9612 -0.4537   2.0     3     5     3   
2                1.0     4 -0.9612 -0.4537   3.0     3     8     3   
3                1.0     3 -1.8176 -0.4537   NaN     3     7     3   
4                3.0     1  0.7516 -0.4537   2.0     2     8     2   

   Attrition_rate  
0          0.1841  
1          0.0670  
2          0.0851  
3          0.0668  
4          0.1827  

[5 rows x 23 columns]

In [7]:
test_set.head()

Gender   Age  Education_Level Relationship_Status     Hometown       Unit  \
0      F  32.0                5              Single  Springfield        R&D   
1      M  65.0                2              Single      Lebanon         IT   
2      M  52.0                3             Married  Springfield      Sales   
3      M  50.0                5              Single   Washington  Marketing   
4      F  44.0                3             Married     Franklin        R&D   

  Decision_skill_possess  Time_of_service  Time_since_promotion  growth_rate  \
0             Conceptual              7.0                     4           30   
1              Directive             41.0                     2           72   
2              Directive             21.0                     3           25   
3             Analytical             11.0                     4           28   
4             Conceptual             12.0                     4           47   

   ...  Pay_Scale  Compensation_and_Benefits  Work_Life_balance VAR1    VAR2  \
0  ...        4.0                      type2                1.0    3 -0.9612   
1  ...        1.0                      type2                1.0    4 -0.9612   
2  ...        8.0                      type3                1.0    4 -0.1048   
3  ...        2.0                      type0                4.0    3 -0.1048   
4  ...        2.0                      type2                4.0    4  1.6081   

     VAR3  VAR4  VAR5  VAR6  VAR7  
0 -0.4537   2.0     1     8     4  
1  0.7075   1.0     2     8     2  
2  0.7075   2.0     1     9     3  
3  0.7075   2.0     2     8     3  
4  0.7075   2.0     2     7     4  

[5 rows x 22 columns]

In [8]:
x = train_set.iloc[:,:-1].values
y = train_set.iloc[:,-1].values
x_test =  test_set.iloc[:,:].values

In [9]:
print(x_test[0])

['F' 32.0 5 'Single' 'Springfield' 'R&D' 'Conceptual' 7.0 4 30 1 5 4.0
 'type2' 1.0 3 -0.9612 -0.4537 2.0 1 8 4]


In [10]:
print(x[0])

['F' 42.0 4 'Married' 'Franklin' 'IT' 'Conceptual' 4.0 4 33 1 1 7.0
 'type2' 3.0 4 0.7516 1.8688 2.0 4 5 3]


In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')
imputer.fit(x[:,[1,2,7,8,9,10,11,12,14,15,16,17,18,19,20,21]])
x[:,[1,2,7,8,9,10,11,12,14,15,16,17,18,19,20,21]] = imputer.transform(x[:,[1,2,7,8,9,10,11,12,14,15,16,17,18,19,20,21]])
x_test[:,[1,2,7,8,9,10,11,12,14,15,16,17,18,19,20,21]] = imputer.transform(x_test[:,[1,2,7,8,9,10,11,12,14,15,16,17,18,19,20,21]])

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()
le4 = LabelEncoder()
le5 = LabelEncoder()
x[:,0] = le.fit_transform(x[:,0])
x_test[:,0] = le.transform(x_test[:,0])
x[:,3] = le1.fit_transform(x[:,3])
x_test[:,3] = le1.transform(x_test[:,3])
x[:,4] = le2.fit_transform(x[:,4])
x_test[:,4] = le2.transform(x_test[:,4])
x[:,5] = le3.fit_transform(x[:,5])
x_test[:,5] = le3.transform(x_test[:,5])
x[:,6] = le4.fit_transform(x[:,6])
x_test[:,6] = le4.transform(x_test[:,6])
x[:,13] = le5.fit_transform(x[:,13])
x_test[:,13] = le5.transform(x_test[:,13])

In [13]:
print(x[0])

[0 42.0 4.0 0 1 2 2 4.0 4.0 33.0 1.0 1.0 7.0 2 3.0 4.0 0.7516 1.8688 2.0
 4.0 5.0 3.0]


In [14]:
print(x)

[[0 42.0 4.0 ... 4.0 5.0 3.0]
 [1 24.0 3.0 ... 3.0 5.0 3.0]
 [0 58.0 3.0 ... 3.0 8.0 3.0]
 ...
 [0 49.0 3.0 ... 4.0 8.0 3.0]
 [0 47.0 3.0 ... 3.0 6.0 3.0]
 [0 58.0 3.0 ... 4.0 5.0 3.0]]


In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x_test = sc.transform(x_test)

In [16]:
print(x)

[[-0.83756018  0.18009898  0.76255659 ...  1.24175608 -1.80495079
  -0.27776175]
 [ 1.19394406 -1.18359795 -0.17638732 ...  0.17665468 -1.80495079
  -0.27776175]
 [-0.83756018  1.39227403 -0.17638732 ...  0.17665468  0.77197263
  -0.27776175]
 ...
 [-0.83756018  0.71042557 -0.17638732 ...  1.24175608  0.77197263
  -0.27776175]
 [-0.83756018  0.55890369 -0.17638732 ...  0.17665468 -0.94597631
  -0.27776175]
 [-0.83756018  1.39227403 -0.17638732 ...  1.24175608 -1.80495079
  -0.27776175]]


In [17]:
from sklearn.model_selection import train_test_split
x_train , x_test1 , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 0)

In [18]:
from sklearn.tree import DecisionTreeRegressor

In [19]:
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x, y)
y_pred = regressor.predict(x_test)
print(y_pred)

[0.04835 0.2966  0.2471  ... 0.0776  0.1976  0.1255 ]


In [20]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x,y)
y_pred = regressor.predict(x_test)
print(y_pred)

[0.3086809  0.31743185 0.16475824 ... 0.17823653 0.37062244 0.23466143]


In [21]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x, y)
y_pred = regressor.predict(x_test)
print(y_pred)

[0.27028  0.31136  0.24664  ... 0.094465 0.26702  0.13919 ]


In [22]:
final_answer = pd.DataFrame({
    'Employee_ID' : test_copy['Employee_ID'],
    'Attrition_rate' : y_pred
})

In [23]:
final_answer.to_csv('submission1_2.csv' , index=False)

In [24]:
final_answer.head()

Employee_ID  Attrition_rate
0   EID_22713         0.27028
1    EID_9658         0.31136
2   EID_22203         0.24664
3    EID_7652         0.31232
4    EID_6516         0.29145

In [41]:
import tensorflow as tf
from tensorflow import keras
ann = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64 , activation = 'relu'),
    tf.keras.layers.Dense(32 , activation = 'relu'),
    tf.keras.layers.Dense(1)
])

In [42]:
ann.compile(optimizer = 'adam' , loss='mean_squared_error')

In [27]:
ann.fit(x_train , y_train , epochs = 100)

Epoch 1/100
5600/5600 [==============================] - 6s 1ms/sample - loss: 0.0545
Epoch 2/100
5600/5600 [==============================] - 1s 90us/sample - loss: 0.0363
Epoch 3/100
5600/5600 [==============================] - 1s 97us/sample - loss: 0.0324
Epoch 4/100
5600/5600 [==============================] - 1s 101us/sample - loss: 0.0301
Epoch 5/100
5600/5600 [==============================] - 1s 103us/sample - loss: 0.0283
Epoch 6/100
5600/5600 [==============================] - 1s 89us/sample - loss: 0.0265
Epoch 7/100
5600/5600 [==============================] - 1s 100us/sample - loss: 0.0252
Epoch 8/100
5600/5600 [==============================] - 1s 94us/sample - loss: 0.0235
Epoch 9/100
5600/5600 [==============================] - 1s 96us/sample - loss: 0.0230
Epoch 10/100
5600/5600 [==============================] - 1s 91us/sample - loss: 0.0207
Epoch 11/100
5600/5600 [==============================] - 1s 89us/sample - loss: 0.0191
Epoch 12/100
5600/5600 [===============

5600/5600 [==============================] - 1s 101us/sample - loss: 0.0019
Epoch 95/100
5600/5600 [==============================] - 1s 99us/sample - loss: 0.0018
Epoch 96/100
5600/5600 [==============================] - 0s 88us/sample - loss: 0.0017
Epoch 97/100
5600/5600 [==============================] - 0s 88us/sample - loss: 0.00170s - loss:
Epoch 98/100
5600/5600 [==============================] - 0s 88us/sample - loss: 0.0017
Epoch 99/100
5600/5600 [==============================] - 1s 89us/sample - loss: 0.0021
Epoch 100/100
5600/5600 [==============================] - 1s 92us/sample - loss: 0.0024


In [ ]:
ann.fit(x ,y ,epochs=100)

Epoch 1/100
7000/7000 [==============================] - 1s 132us/sample - loss: 0.0993
Epoch 2/100
7000/7000 [==============================] - 1s 96us/sample - loss: 0.0441
Epoch 3/100
7000/7000 [==============================] - 1s 93us/sample - loss: 0.0388
Epoch 4/100
7000/7000 [==============================] - 1s 89us/sample - loss: 0.0362
Epoch 5/100
7000/7000 [==============================] - 1s 94us/sample - loss: 0.0345
Epoch 6/100
7000/7000 [==============================] - 1s 95us/sample - loss: 0.0334
Epoch 7/100
7000/7000 [==============================] - 1s 92us/sample - loss: 0.0327
Epoch 8/100
7000/7000 [==============================] - 1s 90us/sample - loss: 0.0318
Epoch 9/100
7000/7000 [==============================] - 1s 93us/sample - loss: 0.0313
Epoch 10/100
7000/7000 [==============================] - 1s 99us/sample - loss: 0.0311
Epoch 11/100
7000/7000 [==============================] - 1s 94us/sample - loss: 0.0303
Epoch 12/100
7000/7000 [================

In [36]:
y_pred = ann.predict(x_test)
print(y_pred)

[[ 0.19]
 [ 0.33]
 [-0.11]
 ...
 [ 0.08]
 [ 0.42]
 [ 0.35]]


In [37]:
y_pred = y_pred.flatten()
print(y_pred)

[ 0.19  0.33 -0.11 ...  0.08  0.42  0.35]


In [38]:
final_answer = pd.DataFrame({
    'Employee_ID' : test_copy['Employee_ID'],
    'Attrition_rate' : y_pred
})

In [39]:
final_answer.to_csv('submission1_3.csv' , index=False)

In [40]:
final_answer.head()

Employee_ID  Attrition_rate
0   EID_22713        0.190224
1    EID_9658        0.333671
2   EID_22203       -0.110160
3    EID_7652        0.227200
4    EID_6516        0.280129